package games.fatboychummy.wideplots.command;

import games.fatboychummy.wideplots.command.arguments.PlotActionTypeArgument;
import games.fatboychummy.wideplots.command.arguments.PlotPermissionArgument;
import games.fatboychummy.wideplots.command.impl.*;
import games.fatboychummy.wideplots.command.impl.claims.*;
import games.fatboychummy.wideplots.command.impl.permissions.*;
import games.fatboychummy.wideplots.command.impl.permissions.update.*;
import games.fatboychummy.wideplots.command.impl.settings.getters.*;
import games.fatboychummy.wideplots.command.impl.settings.setters.*;
import games.fatboychummy.wideplots.command.impl.storage.PlotDownloadCommand;
import games.fatboychummy.wideplots.command.impl.storage.PlotLoadCommand;
import games.fatboychummy.wideplots.command.impl.storage.PlotSaveCommand;
import games.fatboychummy.wideplots.command.impl.storage.PlotWipeCommand;
import games.fatboychummy.wideplots.command.impl.teleportation.PlotTpCommand;
import games.fatboychummy.wideplots.command.impl.teleportation.PlotVisitCommand;
import net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback;
import net.minecraft.commands.Commands;
import net.minecraft.commands.arguments.GameModeArgument;

/**
 * Commands related to plot management, such as claiming, unclaiming, and setting permissions.
 */
public class PlotCommands {
    public static void init() {
        // Prepare any commands that need preparation before registration.
        PlotWipeCommand.init();

        // Register all commands.
        CommandRegistrationCallback.EVENT.register((dispatcher, registryAccess, environment) -> {
            // Displays current dimension and generator.
            dispatcher.register(
                    Commands.literal("plot")
                            .then(Commands.literal("help")
                                    .executes(PlotHelpCommand::execute)
                            )
                            .executes(PlotHelpCommand::execute)
                            .then(Commands.literal("force")
                                    .requires(source -> source.hasPermission(4))
                                    .then(Commands.literal("claim")
                                            .executes(PlotForceClaimCommand::execute)
                                            .then(Commands.argument("player", net.minecraft.commands.arguments.GameProfileArgument.gameProfile())
                                                    .executes(PlotForceClaimCommand::execute)
                                            )
                                    )
                                    .then(Commands.literal("unclaim")
                                            .executes(PlotForceUnclaimCommand::execute)
                                    )
                            )
                            .then(Commands.literal("claim")
                                    .executes(PlotClaimCommand::execute)
                            )
                            .then(Commands.literal("unclaim")
                                    .executes(PlotUnclaimCommand::execute)
                            )
                            .then(Commands.literal("permissions")
                                    .then(Commands.literal("createSet")
                                            .then(Commands.argument("name", com.mojang.brigadier.arguments.StringArgumentType.string())
                                                    .executes(PlotPermissionsCreateSetCommand::execute)
                                            )
                                    )
                                    .then(Commands.literal("getBoundingTool")
                                            .then(Commands.argument("name", com.mojang.brigadier.arguments.StringArgumentType.string())
                                                .executes(PlotPermissionsGetBoundingToolCommand::execute)
                                            )
                                    )
                                    .then(Commands.literal("listSets")
                                            .executes(PlotPermissionsListSetsCommand::execute)
                                    )
                                    .then(Commands.literal("deleteSet")
                                            .then(Commands.argument("name", com.mojang.brigadier.arguments.StringArgumentType.string())
                                                    .executes(PlotPermissionsDeleteSetCommand::execute)
                                            )
                                    )
                                    .then(Commands.literal("updateSet")
                                            .then(Commands.argument("name", com.mojang.brigadier.arguments.StringArgumentType.string())
                                                    .then(Commands.literal("addPlayer")
                                                            .then(Commands.argument("player", net.minecraft.commands.arguments.GameProfileArgument.gameProfile())
                                                                    .executes(PlotPermissionsUpdateSetAddPlayerCommand::execute)
                                                            )
                                                    )
                                                    .then(Commands.literal("removePlayer")
                                                            .then(Commands.argument("player", net.minecraft.commands.arguments.GameProfileArgument.gameProfile())
                                                                    .executes(PlotPermissionsUpdateSetRemovePlayerCommand::execute)
                                                            )
                                                    )
                                                    .then(Commands.literal("addBlock")
                                                            .then(Commands.argument("block", net.minecraft.commands.arguments.ResourceLocationArgument.id())
                                                                    .executes(PlotPermissionsUpdateSetAddBlockCommand::execute)
                                                            )
                                                    )
                                                    .then(Commands.literal("removeBlock")
                                                            .then(Commands.argument("block", net.minecraft.commands.arguments.ResourceLocationArgument.id())
                                                                    .executes(PlotPermissionsUpdateSetRemoveBlockCommand::execute)
                                                            )
                                                    )
                                                    .then(Commands.literal("setPlayerWhitelist")
                                                            .executes(PlotPermissionsUpdateSetSetPlayerWhitelistCommand::execute)
                                                    )
                                                    .then(Commands.literal("setPlayerBlacklist")
                                                            .executes(PlotPermissionsUpdateSetSetPlayerBlacklistCommand::execute)
                                                    )
                                                    .then(Commands.literal("setBlockWhitelist")
                                                            .executes(PlotPermissionsUpdateSetSetBlockWhitelistCommand::execute)
                                                    )
                                                    .then(Commands.literal("setBlockBlacklist")
                                                            .executes(PlotPermissionsUpdateSetSetBlockBlacklistCommand::execute)
                                                    )
                                                    .then(Commands.literal("setActive")
                                                            .then(Commands.argument("active", com.mojang.brigadier.arguments.BoolArgumentType.bool())
                                                                    .executes(PlotPermissionsUpdateSetSetActiveCommand::execute)
                                                            )
                                                    )
                                                    .then(Commands.literal("setPriority")
                                                            .then(Commands.argument("priority", com.mojang.brigadier.arguments.IntegerArgumentType.integer())
                                                                    .executes(PlotPermissionsUpdateSetSetPriorityCommand::execute)
                                                            )
                                                    )
                                                    .then(Commands.literal("setPermission")
                                                            .then(Commands.argument("action", PlotActionTypeArgument.action())
                                                                    .then(Commands.argument("permission", PlotPermissionArgument.action())
                                                                            .executes(PlotPermissionsUpdateSetSetPermissionCommand::execute)
                                                                    )
                                                            )
                                                    )
                                            )
                                    )
                            )
                            .then(Commands.literal("info")
                                    .executes(PlotInfoCommand::execute)
                            )
                            .then(Commands.literal("visit")
                                    .then(Commands.argument("player", net.minecraft.commands.arguments.GameProfileArgument.gameProfile())
                                            .then(Commands.argument("plotName", com.mojang.brigadier.arguments.StringArgumentType.string())
                                                .executes(PlotVisitCommand::execute)
                                            )
                                    )
                            )
                            .then(Commands.literal("trust")
                                    .then(Commands.argument("player", net.minecraft.commands.arguments.GameProfileArgument.gameProfile())
                                            .executes(PlotTrustCommand::execute)
                                    )
                            )
                            .then(Commands.literal("untrust")
                                    .then(Commands.argument("player", net.minecraft.commands.arguments.GameProfileArgument.gameProfile())
                                            .executes(PlotUntrustCommand::execute)
                                    )
                            )
                            .then(Commands.literal("kick")
                                    .then(Commands.argument("player", net.minecraft.commands.arguments.GameProfileArgument.gameProfile())
                                            .executes(PlotKickCommand::execute)
                                    )
                            )
                            .then(Commands.literal("ban")
                                    .then(Commands.argument("player", net.minecraft.commands.arguments.EntityArgument.player())
                                            .executes(PlotBanCommand::execute)
                                    )
                            )
                            .then(Commands.literal("unban")
                                    .then(Commands.argument("player", net.minecraft.commands.arguments.GameProfileArgument.gameProfile())
                                            .executes(PlotUnbanCommand::execute)
                                    )
                            )
                            .then(Commands.literal("tp")
                                    .executes(PlotTpCommand::execute)
                            )
                            .then(Commands.literal("wipe")
                                    .executes(PlotWipeCommand::execute)
                            )
                            .then(Commands.literal("save")
                                    .then(Commands.argument("name", com.mojang.brigadier.arguments.StringArgumentType.string())
                                            .executes(PlotSaveCommand::execute)
                                    )
                            )
                            .then(Commands.literal("load")
                                    .then(Commands.argument("name", com.mojang.brigadier.arguments.StringArgumentType.string())
                                            .executes(PlotLoadCommand::execute)
                                    )
                            )
                            .then(Commands.literal("download")
                                    .executes(PlotDownloadCommand::execute) // Downloads the current plot.
                                    .then(Commands.argument("name", com.mojang.brigadier.arguments.StringArgumentType.string())
                                            .executes(PlotDownloadCommand::execute) // Downloads the specified saved plot.
                                    )
                            )
                            .then(Commands.literal("settings")
                                    .then(Commands.literal("set")
                                            .then(Commands.literal("name")
                                                    .then(Commands.argument("name", com.mojang.brigadier.arguments.StringArgumentType.string())
                                                            .executes(PlotSettingsSetNameCommand::execute)
                                                    )
                                            )
                                            .then(Commands.literal("description")
                                                    .then(Commands.argument("description", com.mojang.brigadier.arguments.StringArgumentType.string())
                                                            .executes(PlotSettingsSetDescriptionCommand::execute)
                                                    )
                                            )
                                            .then(Commands.literal("visitorTeleportLocation")
                                                    .executes(PlotSettingsSetVisitorLocationCommand::execute)
                                            )
                                            .then(Commands.literal("welcomeMessage")
                                                    .then(Commands.argument("welcomeMessage", com.mojang.brigadier.arguments.StringArgumentType.string())
                                                            .executes(PlotSettingsSetWelcomeMessageCommand::execute)
                                                    )
                                            )
                                            .then(Commands.literal("departureMessage")
                                                    .then(Commands.argument("departureMessage", com.mojang.brigadier.arguments.StringArgumentType.string())
                                                            .executes(PlotSettingsSetDepartureMessageCommand::execute)
                                                    )
                                            )
                                            .then(Commands.literal("gamemode")
                                                    .then(Commands.argument("gamemode", GameModeArgument.gameMode())
                                                            .executes(PlotSettingsSetGamemodeCommand::execute)
                                                    )
                                            )
                                    )
                                    .then(Commands.literal("get")
                                            .then(Commands.literal("name")
                                                    .executes(PlotSettingsGetNameCommand::execute)
                                            )
                                            .then(Commands.literal("description")
                                                    .executes(PlotSettingsGetDescriptionCommand::execute)
                                            )
                                            .then(Commands.literal("visitorTeleportLocation")
                                                    .executes(PlotSettingsGetVisitorLocationCommand::execute)
                                            )
                                            .then(Commands.literal("welcomeMessage")
                                                    .executes(PlotSettingsGetWelcomeMessageCommand::execute)
                                            )
                                            .then(Commands.literal("departureMessage")
                                                    .executes(PlotSettingsGetDepartureMessageCommand::execute)
                                            )
                                            .then(Commands.literal("gamemode")
                                                    .executes(PlotSettingsGetGamemodeCommand::execute)
                                            )
                                    )
                            )
            );
        });
    }
}
